### ISSUE TITLE
Verify DNS server settings

### ISSUE THREAD

**Issue by origooo** [aws-samples/aws-network-firewall-rulegroups-with-proofpoints-emerging-threats-open-ruleset#1]
Hi! Love your piece of code!

I recently implemented this for my firewall and all IPS rules are generated and updated as expected. However, a few questions which arose was;

1. Can I verify that the DNS I supplied is correct, and what effect does it have if I choose the wrong DNS? I found it hard to understand what my VPC's DNS is, but I understood it as if my VPC CIDR is e.g. 10.10.0.0/16, then my DNS would be 10.10.0.2. Is that correct?

2. Is there any downfall to setting the whole CIDR as $HTTPSERVERS?

3. I was also wondering if you know about a certain standard for what rules groups to use for a standard web setup?

**Comment by pandrel** [comment]
Hello @origooo , 

Thank you for your interest in this sample code. Please find below response to your questions 
 
 
> 1. Can I verify that the DNS I supplied is correct, and what effect does it have if I choose the wrong DNS? I found it hard to understand what my VPC's DNS is, but I understood it as if my VPC CIDR is e.g. 10.10.0.0/16, then my DNS would be 10.10.0.2. Is that correct?

That is correct if you have enableDnsSupport=true for the vpc. Although some organizations disable this default setting and use different dns servers like DNS provided by Active Directory. In such scenarios you have to provide the AD dns servers list. 

> 2. Is there any downfall to setting the whole CIDR as $HTTPSERVERS?  

No. I have used the whole CIDR during my testing.  

> 3. I was also wondering if you know about a certain standard for what rules groups to use for a standard web setup?  

Unfortunately, i am primarily a developer of this use-case not an expert on Network firewall or Emerging threats. Although, I would recommend to research more on proofpoint forums for further guidance on this.

**Comment by pandrel** [comment]
@origooo Hope i have answered your questions. This issue will closed after 3 days if there are no further responses.

**Comment by pandrel** [comment]
Resolving issue as there is no further response.
